name: Update API specs
on:
  workflow_dispatch:
  # Run daily after midnight UTC
  schedule:
  - cron: '0 1 * * *'

jobs:
  backport:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Determine versions
      id: versions
      run: |
        echo "base=$(cat .base_version)" >> "$GITHUB_OUTPUT"
        echo "snap=$(snap info anbox-cloud-appliance | awk '/installed/{print $2}')" >> "$GITHUB_OUTPUT"
    - name: Setup Anbox Cloud
      uses: canonical/anbox-cloud-github-action@39490d442cc0921fe614f7044b9f3dc8bd89725c
      with:
        channel: ${{ steps.versions.outputs.base }}/stable
    - name: Extra API spec from AMS
      run:
        sudo apt install -y yq
        curl \
          --unix-socket /var/snap/anbox-cloud-appliance/common/ams-unix.socket \
          s/1.0/swagger.json | yq -P > ./reference/api-reference/ams-api.yaml
    - name: Create PR
      uses: canonical/create-pull-request@5b97f11bd11d44ed8c4ad49f60d6f529374b1e87
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: update API specs from ${{ steps.versions.outputs.snap }}"
        branch-name: new-branch
        title: Update API specs from ${{ steps.versions.outputs.snap }}
        body: |
          This updates the AMS API specification as taken from the `anbox-cloud-appliance` as of
          version ${{ steps.versions.outputs.snap }}.
        repository: canonical/anbox-cloud-docs
        upsert: true
        ignore-no-changes: true
